language: rust


cache: 
  timeout: 360
  cargo: true

before_cache:
  - chmod -R a+r $HOME/.cargo

env:
  global:
    - CRATE_NAME=upt

matrix:
  include:
    - os: linux
      dist: trusty
      env: TARGET=i686-unknown-linux-musl
      rust: stable
    - os: linux
      dist: trusty
      env: TARGET=x86_64-unknown-linux-musl
      rust: stable
    - os: osx
      env: TARGET=x86_64-apple-darwin
      rust: stable
    - os: linux
      dist: trusty
      env: TARGET=x86_64-unknown-linux-musl
      rust: nightly
    - os: osx
      rust: nightly
      env: TARGET=x86_64-apple-darwin

test_script:
  - cargo test 
  - cargo run -- list -i

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: "cI3Uj4zeA4UowGXpH3Qk7ZSyKeNjmYGXGgJIRIaGACtNpmWfoRdeuUrIi5jw0eBUFCuntwVMlEKaZa00U1kovdoTuXeum8QJ4y90s6PaSsCFkSlLi5uLe2txq8QP4c6Vs6tpK8T8B8CPiLQl0J/7IDiTC/BfVzJetQv7zZ77OAV9T2PR9hX/3z9+Itk6Xul0FPavXfhh7urUK9Qr/lHO4uaRmH0gNAAx4sv+fGYp/w8bFKfHzNwyVGt7yxEYQKPsC/qBTz7gcC1rxWDGdLZ6GsuS5AoQ3pXASmEpOMeHgEYk5PEWDUICt4KGI5pc7a0r7qW4FgxyxkwSu+L/cZyMTXky1r7A/tXcv7Dy/CaCK0mMt0gkOOVrnsQ3dnTH2Cg8iNtIBUsF2MrrcIA9tCypsu4RZtWzCJcSGW8MSIF6QEAUC0ZQE3xzQb52O20h8x1GEEyL5Stg9KRMIGG9BdhjFknJFAzEKyVtCY94wx6ryMp5Q4pyVEj07Xijr98Ox2j1TrHdULnOVYPKcIhxytAzIMGJogVatNsbQJuKmnpklhK2sMnCcMIg4YrUKydTNLHiWdvcV4aMrd8knnT6/Gvms676c2z1B9udj3rn1HylNIWADfOyEGoGds/OJ11FQ5i0XJeFLPszex4r9RwDvcnLtXlX+zhxVZx/9q8P1Gb3M6E="
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true

branches:
  only:
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
